[project]
name = "vectordb-benchmark-vix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.2.0",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]
